RECORD_BUFFER_SIZE = 8000
RECORD_READ_BUFFER_SIZE = 100
RECORD_RATE = 8000

WINDOW_SIZE = 2048

DAMPEN = 0.9
MAX_DAMPEN = 0.99

COLUMNS = 75
DISPLAY_COLUMNS = 50

TIME = 3.0
FILENAME = "/tmp/datafile.m"
