RECORD_BUFFER_SIZE = 8000
RECORD_READ_BUFFER_SIZE = 100
RECORD_RATE = 8000

WINDOW_SIZE = 2048

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 360

DAMPEN = 0.9
MAX_DAMPEN = 0.99

COLUMNS = 30
DISPLAY_COLUMNS = 20

NA_ROWS = 50
NA_SPEED = 3.0
NA_CAM_HEIGHT = 0.4
NA_BASE_HEIGHT = 0.2
NA_AMPLITUDE_TOP = 0.7
NA_AMPLITUDE_BOTTOM = 0.1
NA_MID_DISTANCE = 0.3
NA_DEPTH = 30.0
