RECORD_BUFFER_SIZE = 8000
RECORD_READ_BUFFER_SIZE = 100
RECORD_RATE = 8000

WINDOW_SIZE = 2048

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

DAMPEN = 0.8
MAX_DAMPEN = 0.99

COLUMNS = 30
DISPLAY_COLUMNS = 20

# Number of rows
NA_ROWS = 50

# Movement speed
NA_SPEED = 1.0
NA_SPEED_DAMPEN = 0.995
NA_SPEED_DEVIATION = 0.5

# Height of camera above the z = 0 plane
NA_CAM_HEIGHT = 0.8

# Maximum camera movement
NA_SHAKE = 0.06

# FOV changes
NA_FOV_MIN = 3.0
NA_FOV_MAX = 4.0

# Minimum height of grid lines
NA_BASE_HEIGHT = 0.2

# Maximum amplitude of grid lines on the upper half
NA_AMPLITUDE_TOP = 0.7

# Maximum amplitude of grid lines on the lower half
NA_AMPLITUDE_BOTTOM = 0.1

# Distance between left and right channel
NA_MID_DISTANCE = 0.3

# How far back the rows go (Zfar is 100)
NA_DEPTH = 30.0

# Maximum number of simultaneous lightnings (approximate)
NA_LN_MAX = 15

# Maximum number of points per lightning
NA_LN_PMAX = 10

# Maximum number of lines per lightning
NA_LN_LMAX = 26

# Factor for dimming the lightning
# Lower is faster
NA_LN_DIM = 0.95

# Lightning size factor
NA_LN_SIZE = 1.0

# Lightning deformation factor
# Higher means more width and less height
NA_LN_SIZE_DF = 1.2

# Minimum time between lightnings
NA_LN_TIMEOUT = 0.06

NA_LN_BEAT_MINVOLUME = 70.0

# What spectrum columns to watch for the beat
[[NA_LN_BEAT_COLS]]
c = 16
s = 0.25

[[NA_LN_BEAT_COLS]]
c = 16
s = 0.35

[[NA_LN_BEAT_COLS]]
c = 25
s = 0.5

[[NA_LN_BEAT_COLS]]
c = 40
s = 0.16
