RECORD_BUFFER_SIZE = 8000
RECORD_READ_BUFFER_SIZE = 100
RECORD_RATE = 8000

WINDOW_SIZE = 2048

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900

DAMPEN = 0.9
MAX_DAMPEN = 0.99

COLUMNS = 30
DISPLAY_COLUMNS = 20

# SIMPLE_RIGHT_CHANNEL = true
# SIMPLE_RIGHT_CHANNEL_MIDDLE = true
# SIMPLE_RIGHT_CHANNEL_COLOR_OFFSET = true
SIMPLE_SYMMETRIC_MODE = true
