RECORD_BUFFER_SIZE = 8000
RECORD_READ_BUFFER_SIZE = 100
RECORD_RATE = 8000

WINDOW_SIZE = 2048

# WINDOW_WIDTH = 640
# WINDOW_HEIGHT = 360
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

DAMPEN = 0.8
MAX_DAMPEN = 0.99

COLUMNS = 200
DISPLAY_COLUMNS = 75

SPACE_CAMERA_SPEED = 5.0
SPACE_CAMERA_HEIGHT = 0.2
SPACE_CAMERA_RADIUS = 2.0

SPACE_STATION_ROT_FACTOR = 0.1
SPACE_STATION_BASE_ROT = 0.3

SPACE_SHIP_TIMEOUT = 0.06

[fdrop]
min = 0.02
max = 0.08
num = 5
timeout = 0.2
random = false
start_column = 15

[planet]
x = -10.0
y = -12.0
z = -28.0
scale = 12.0

# What spectrum columns to watch for the beat
[[SPACE_BEAT_COLS]]
c = 16
s = 0.25

[[SPACE_BEAT_COLS]]
c = 16
s = 0.35

[[SPACE_BEAT_COLS]]
c = 25
s = 0.5

[[SPACE_BEAT_COLS]]
c = 40
s = 0.16
